name: Update G-code Documentation

on:
  workflow_dispatch: # Allows manual runs
  schedule:
    - cron: '0 0 1 * *' # Runs on the 1st of every month at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run G-code documentation parser
        run: |
          python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/all_codes.json
          git commit -m "Update all_codes.json with latest G-code documentation"
          git push
        env:
          # Use GitHub's built-in token for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
